const arraySet = [
    ["Apple", "Banana", "Orange"],
    ["Cat", "Dog", "Fish"],
    ["Red", "Green", "Blue"],
    ["Chair", "Table", "Couch"],
    ["Elephant", "Giraffe", "Lion"],
    ["Sun", "Moon", "Stars"],
    ["Coffee", "Tea", "Cocoa"],
    ["Car", "Bicycle", "Motorcycle"],
    ["Pizza", "Burger", "Pasta"],
    ["Winter", "Spring", "Summer"],
    ["Pencil", "Pen", "Marker"],
    ["Mountain", "Ocean", "Desert"],
    ["Guitar", "Piano", "Violin"],
    ["Rose", "Tulip", "Daisy"],
    ["Computer", "Phone", "Tablet"],
    ["Football", "Basketball", "Soccer"],
    ["Plane", "Train", "Boat"],
    ["Gold", "Silver", "Bronze"],
    ["Doctor", "Teacher", "Engineer"],
    ["Rain", "Snow", "Hail"],
    ["Chocolate", "Vanilla", "Strawberry"],
    ["Australia", "Brazil", "Japan"],
    ["Fire", "Water", "Air"],
    ["Eagle", "Owl", "Hawk"],
    ["Hiking", "Cycling", "Running"],
    ["Diamond", "Ruby", "Emerald"],
    ["Rainbow", "Cloud", "Sunshine"],
    ["Library", "Museum", "Gallery"],
    ["Swimming", "Skiing", "Surfing"],
    ["Doctor", "Nurse", "Paramedic"],
    ["Ferrari", "Lamborghini", "Tesla"],
    ["Spider", "Ant", "Butterfly"],
    ["Novel", "Poetry", "Short Story"],
    ["Chess", "Checkers", "Backgammon"],
    ["Robot", "Alien", "Human"],
    ["Maple", "Oak", "Pine"],
    ["Jazz", "Rock", "Classical"],
    ["Telescope", "Microscope", "Binoculars"],
    ["Dolphin", "Whale", "Shark"],
    ["Frog", "Snake", "Turtle"],
    ["Safari", "Cruise", "Road Trip"],
    ["Mercedes", "BMW", "Audi"],
    ["Chocolate", "Caramel", "Nougat"],
    ["Cactus", "Rosemary", "Lavender"],
    ["Chocolate", "Chip", "Oatmeal"],
    ["Snorkeling", "Scuba Diving", "Sailing"],
    ["Van Gogh", "Picasso", "Da Vinci"],
    ["Detective", "Spy", "Agent"],
    ["Romance", "Action", "Comedy"],
    ["Banjo", "Harmonica", "Accordion"],
    ["Lighthouse", "Windmill", "Waterfall"],
    ["Dragonfly", "Ladybug", "Beetle"],
    ["Tiger", "Leopard", "Cheetah"]
    ];